language: objective-c
osx_image: xcode9.2

before_install:
  - gem install xcpretty
before_script:
  - set -o pipefail
script:
  - xcodebuild
    -project SwiftGif.xcodeproj
    -scheme SwiftGif
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 8" build test
    CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
